import type { Metadata } from "next";
import { Nunito_Sans} from "next/font/google";
import '@/scss/styles.scss';


import { Header } from "@/components/layout/header/Header";
import { Footer } from "@/components/layout/footer/Footer";

const nunitoSans = Nunito_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
